version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amar-assist-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - amar-assist-network

  nginx:
    image: nginx:alpine
    container_name: amar-assist-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - amar-assist-network

  db:
    image: mysql:8.0
    container_name: amar-assist-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_USER: ${DB_USERNAME:-laravel}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - amar-assist-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: amar-assist-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "8080:80"
    networks:
      - amar-assist-network

networks:
  amar-assist-network:
    driver: bridge

volumes:
  dbdata: 